/// <reference path="core.ts" />
tui.dict("en-us", {
    "success": "Success",
    "warning": "Warning",
    "confirm": "Confirm",
    "note": "Note",
    "notmodified": "Request's content has not been modified!",
    "error": "Error",
    "timeout": "Request timeout!",
    "abort": "Operating has been aborted!",
    "parsererror": "Server response invalid content!",
    "ok": "OK",
    "close": "Close",
    "cancel": "Cancel",
    "accept": "Accept",
    "agree": "Agree",
    "reject": "Reject",
    "yes": "Yes",
    "no": "No",
    "select": "Select",
    "please.select.point": "Please select a point of the map.",
    "address": "Address",
    "invalid.file.type": "Invalid file type!",
    "geo.location.failed": "Get current location failed, please check your browser whether can use geo-location service.",
    "form.section": "Title",
    "form.textbox": "Textbox",
    "form.textarea": "Textarea",
    "form.options": "Options",
    "form.select": "Select",
    "form.datepicker": "Date",
    "form.picture": "Picture",
    "form.file": "File",
    "form.files": "Files",
    "form.grid": "Grid",
    "form.address": "Address",
    "form.properties": "Properties",
    "form.field.name": "Field Name",
    "form.precondition": "Precondition",
    "form.validation": "Validation",
    "form.formula": "Formula",
    "form.message": "Message",
    "form.required": "Required",
    "form.disable": "Disabled",
    "form.description": "Special Instructions"
});
