/// <reference path="core.ts" />
tui.dict("en-us", {
	"allow.append": "Allow Append",
	"allow.delete": "Allow Delete",
	"allow.edit": "Allow Edit",
	"auto.height": "Auto Height",
	"auto.column.width": "Auto Column Width",
	"success": "Success",
	"warning": "Warning",
	"confirm": "Confirm",
	"normal": "Normal",
	"note": "Note",
	"notmodified": "Request's content has not been modified!",
	"error": "Error",
	"timeout": "Request timeout!",
	"abort": "Operating has been aborted!",
	"parsererror": "Server response invalid content!",
	"ok": "OK",
	"close": "Close",
	"cancel": "Cancel",
	"accept": "Accept",
	"agree": "Agree",
	"append": "Append",
	"delete": "Delete",
	"edit": "Edit",
	"reject": "Reject",
	"yes": "Yes",
	"no": "No",
	"finish": "Finish",
	"select": "Select",
	"vertical": "Vertical",
	"please.select.point": "Please select a point of the map.",
	"address": "Address",
	"invalid.file.type": "Invalid file type!",
	"geo.location.failed": "Get current location failed, please check your browser whether can use geo-location service.",
	"form.grid.features": "Features",
	"form.section": "Title",
	"form.textbox": "Textbox",
	"form.textarea": "Textarea",
	"form.options": "Options",
	"form.option.group": "Option Group",
	"form.selection": "Selection",
	"form.selection.desc": "Allow have multiple selection groups it can use condition expression to decide which group come into force.",
	"form.datepicker": "Date",
	"form.picture": "Picture",
	"form.file": "File",
	"form.files": "Files",
	"form.grid": "Grid",
	"form.address": "Address",
	"form.common": "Common",
	"form.field.name": "Field Name",
	"form.precondition": "Precondition",
	"form.validation": "Validation",
	"form.format": "Format",
	"form.message": "Message",
	"form.required": "Required",
	"form.disable": "Disabled",
	"form.enable": "Enabled",
	"form.use.search": "Enable Search",
	"form.description": "Description",
	"form.textbox.selection.desc": "A group predefined input content, separated with newline characters.",
	"form.value.as.label": "Use value as label",
	"message.cannot.be.empty": "Cannot be empty!",
	"message.invalid.format": "Invalid format!",
	"message.invalid.value": "Invalid value!",
	"form.text.align": "Text Align",
	"form.align": "Align",
	"form.align.left": "Left",
	"form.align.center": "Center",
	"form.align.right": "Right",
	"form.font.size": "Font Size",
	"form.input.type": "Input Type",
	"form.text": "Text",
	"form.password": "Password",
	"form.email": "EMail",
	"form.url": "URL",
	"form.number": "Number",
	"form.at.least": "At Least",
	"form.at.most": "At Most",
	"form.at.least.p": "At Least select {0} item(s).",
	"form.at.most.p": "At Most select {0} item(s).",
	"file.count.p": "{0} file(s)",
	"item.count.p": "{0} item(s)",
	"form.option.group.desc": "Options separated by newline, option can be a key:value pair or a string.",
	"form.value": "Value",
	"form.display": "Display",
	"form.invisible": "Invisible",
	"form.visible": "Visible",
	"form.max.height": "Max Height",
	"form.date": "Date",
	"form.date.time": "Date Time",
	"form.time": "Time",
	"form.month": "Year Month",
	"form.custom.format": "Custom Format",
	"form.date.desc": "e.g.: 'yyyy-MM-dd HH:mm:sszz' or 'dd MMM yy hh:mm:ss A', etc..",
	"form.timezone": "Timezone",
	"form.tz.utc": "UTC",
	"form.tz.locale": "Locale",
	"form.tz.none": "None",
	"form.upload.url": "Upload URL",
	"form.file.type": "File Type",
	"message.must.be.image": "Must be valid image mime types.",
	"form.newline": "Newline Only",
	"form.height": "Height",
	"form.design": "Design",
	"form.app.key": "Map App Key",
	"form.emphasize": "Emphasized",
	"message.not.available": "Not Available",
	"form.init.by.current.time": "Use Current Time as Init Value",
	"apply": "应用",
	"rerresh": "刷新",
	"second": "秒",
	"seconds": "秒",
	"minute": "分",
	"minutes": "分",
	"hour": "小时",
	"hours": "小时",
	"day": "天",
	"days": "天",
	"week": "周",
	"weeks": "周",
	"month": "月",
	"months": "月",
	"year": "年",
	"years": "年",
	"previous": "上一页",
	"next": "下一页",
	"january": "一月",
	"february": "二月",
	"march": "三月",
	"april": "四月",
	"may": "五月",
	"june": "六月",
	"july": "七月",
	"august": "八月",
	"september": "九月",
	"october": "十月",
	"november": "十一月",
	"december": "十二月",
	"jan": "一月",
	"feb": "二月",
	"mar": "三月",
	"apr": "四月",
	"jun": "六月",
	"jul": "七月",
	"aug": "八月",
	"sep": "九月",
	"oct": "十月",
	"nov": "十一月",
	"dec": "十二月",
	"sun": "日",
	"mon": "一",
	"tue": "二",
	"wed": "三",
	"thu": "四",
	"fri": "五",
	"sat": "六",
	"today": "今天",
	"clear": "清除",
	"Fill": "填充",
	"New Line": "换行"
});
