/// <reference path="core.ts" />
tui.dict("en-us", {
    "success": "Success",
    "warning": "Warning",
    "confirm": "Confirm",
    "normal": "Normal",
    "note": "Note",
    "notmodified": "Request's content has not been modified!",
    "error": "Error",
    "timeout": "Request timeout!",
    "abort": "Operating has been aborted!",
    "parsererror": "Server response invalid content!",
    "ok": "OK",
    "close": "Close",
    "cancel": "Cancel",
    "accept": "Accept",
    "agree": "Agree",
    "reject": "Reject",
    "yes": "Yes",
    "no": "No",
    "select": "Select",
    "vertical": "Vertical",
    "please.select.point": "Please select a point of the map.",
    "address": "Address",
    "invalid.file.type": "Invalid file type!",
    "geo.location.failed": "Get current location failed, please check your browser whether can use geo-location service.",
    "form.section": "Title",
    "form.textbox": "Textbox",
    "form.textarea": "Textarea",
    "form.options": "Options",
    "form.option.group": "Option Group",
    "form.selection": "Selection",
    "form.selection.desc": "Allow have multiple selection groups it can use condition expression to decide which group come into force.",
    "form.datepicker": "Date",
    "form.picture": "Picture",
    "form.file": "File",
    "form.files": "Files",
    "form.grid": "Grid",
    "form.address": "Address",
    "form.common": "Common",
    "form.field.name": "Field Name",
    "form.precondition": "Precondition",
    "form.validation": "Validation",
    "form.format": "Format",
    "form.message": "Message",
    "form.required": "Required",
    "form.disable": "Disabled",
    "form.enable": "Enabled",
    "form.use.search": "Enable Search",
    "form.description": "Description",
    "form.textbox.selection.desc": "A group predefined input content, separated with newline characters.",
    "message.cannot.be.empty": "Cannot be empty!",
    "message.invalid.format": "Invalid format!",
    "message.invalid.value": "Invalid value!",
    "form.text.align": "Text Align",
    "form.align": "Align",
    "form.align.left": "Left",
    "form.align.center": "Center",
    "form.align.right": "Right",
    "form.font.size": "Font Size",
    "form.input.type": "Input Type",
    "form.text": "Text",
    "form.password": "Password",
    "form.email": "EMail",
    "form.url": "URL",
    "form.number": "Number",
    "form.at.least": "At Least",
    "form.at.most": "At Most",
    "form.at.least.p": "At Least select {0} item(s).",
    "form.at.most.p": "At Most select {0} item(s).",
    "form.option.group.desc": "Options separated by newline, option can be a key:value pair or a string.",
    "form.value": "Value",
    "form.display": "Display",
    "form.invisible": "Invisible",
    "form.visible": "Visible",
    "form.max.height": "Max Height",
    "form.date": "Date",
    "form.date.time": "Date And Time",
    "form.time": "Time",
    "form.month": "Year And Month",
    "form.custom.format": "Custom Format",
    "form.date.desc": "e.g.: 'yyyy-MM-dd HH:mm:sszz' or 'dd MMM yy hh:mm:ss A', etc..",
    "form.timezone": "Timezone",
    "form.tz.utc": "UTC",
    "form.tz.locale": "Locale",
    "form.tz.none": "None",
    "form.upload.url": "Upload URL",
    "form.file.type": "File Type",
    "message.must.be.image": "Must be valid image mime types."
});
